export const INCREMENT_ENTHUSIASM = 'INCREMENT_ENTHUSIASM';
export type INCREMENT_ENTHUSIASM = typeof INCREMENT_ENTHUSIASM;

export const DECREMENT_ENTHUSIASM = 'DECREMENT_ENTHUSIASM';
export type DECREMENT_ENTHUSIASM = typeof DECREMENT_ENTHUSIASM;

export const GET_RESULTS = 'GET_RESULTS';
export type GET_RESULTS = typeof GET_RESULTS;

export const RESULTS_LOADING = 'RESULTS_LOADING';
export type RESULTS_LOADING = typeof RESULTS_LOADING;

export const GET_RESULTS_RESOLVED = 'GET_RESULTS_RESOLVED';
export type GET_RESULTS_RESOLVED = typeof GET_RESULTS_RESOLVED;

export const GET_REJECTED = 'GET_REJECTED';
export type GET_REJECTED = typeof GET_REJECTED;